# Generated by Django 5.1.7 on 2025-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_client_name_policy_policy_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_num',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
